apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: ingress-srv.com
      http:
        paths:
          - path: /api/platforms
            pathType: Prefix
            backend:
              service:
                name: microservicedemo-clusterip-srv
                port:
                  number: 80
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: microservicedemo-clusterip-srv
                port:
                  number: 80
          - path: /api/c
            pathType: Prefix
            backend:
              service:
                name: commands-clusterip-srv
                port:
                  number: 80
          - path: /commands/swagger
            pathType: Prefix
            backend:
              service:
                name: commands-clusterip-srv
                port:
                  number: 80
