apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicedemo
  template:
    metadata:
      labels:
        app: microservicedemo
    spec:
      containers:
      - name: microservicedemo
        image: gokobro/microservicedemo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: microservicedemo-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: microservicedemo
  ports:
  - name: microservicedemo
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: microservicedemo-grpc
    protocol: TCP
    port: 666
    targetPort: 666
