apiVersion: v1
kind: Service
metadata:
  name: microservicedemo-np-srv
spec:
  type: NodePort
  selector:
    app: microservicedemo
  ports:
  - name: microservicedemo
    protocol: TCP
    port: 80
    targetPort: 80

