apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicedemo
  template:
    metadata:
      labels:
        app: microservicedemo
    spec:
      containers:
      - name: microservicedemo
        image: gokobro/gokhnesen:v1
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"